services:
  - type: web
    name: heal-app
    runtime: node
    startCommand: npm install && node server.js
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_ENV
        value: production
