// Re-export transport-specific hooks from useDatabase
export {
  useDrivers,
  useCreateDriver,
  useUpdateDriver,
  useDeleteDriver,
  useVehicles,
  useCreateVehicle,
  useUpdateVehicle,
  useDeleteVehicle,
  useMaterials,
  useCreateMaterial,
  useUpdateMaterial,
  useDeleteMaterial,
  useTransportFinance,
  useCreateTransportFinance,
  useUpdateTransportFinance,
  useDeleteTransportFinance,
  useTransportPayments,
  useTransportPaymentsSummary,
  useCreateTransportPayment,
  useUpdateTransportPayment,
  useDeleteTransportPayment,
} from './useDatabase';
