// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallbacks
// Note: Vite only exposes VITE_ prefixed variables via import.meta.env
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ||
                                import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check for missing configuration
const isMissingConfig = !SUPABASE_URL || SUPABASE_URL === 'undefined' ||
                       !SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'undefined';

if (isMissingConfig) {
  console.warn('⚠️ Supabase configuration is missing.');
  console.warn('   VITE_SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL ? '✓ Set' : '✗ Missing');
  console.warn('   VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY ? '✓ Set' : '✗ Missing');
  console.warn('   App will continue with limited functionality.');
}

// Lazy initialize the Supabase client
let supabaseInstance: any = null;

function getSupabaseClient() {
  if (supabaseInstance) {
    return supabaseInstance;
  }

  if (isMissingConfig) {
  console.error('❌ Cannot initialize Supabase: Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY');
  console.error('   Required environment variables:');
  console.error('   - VITE_SUPABASE_URL (your Supabase project URL)');
  console.error('   - VITE_SUPABASE_ANON_KEY (your Supabase publishable/anon key)');
  // Return a mock client that allows the app to continue running
  return createMockClient();
}

  console.log('✅ Supabase client initialized with URL:', SUPABASE_URL!.substring(0, 30) + '...');

  supabaseInstance = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  return supabaseInstance;
}

function createMockClient() {
  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null } }),
      signInWithPassword: async () => ({ error: new Error('Supabase not configured') }),
      signUp: async () => ({ error: new Error('Supabase not configured') }),
      signOut: async () => ({ error: new Error('Supabase not configured') }),
    },
    from: () => ({
      select: () => Promise.reject(new Error('Supabase not configured')),
      insert: () => Promise.reject(new Error('Supabase not configured')),
      update: () => Promise.reject(new Error('Supabase not configured')),
      delete: () => Promise.reject(new Error('Supabase not configured')),
    }),
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = getSupabaseClient();
